# machine:
#   java:
#     version: circleci/node:7.10
#   services:
#     - docker
deployment:
  hub:
    branch: json-ld
    commands:
      - docker build -t $REPO .
      - docker tag $REPO $REPO:$CIRCLE_BUILD_NUM
      - docker login -u $USER -e $EMAIL -p $PASS
      - docker push $REP